project_id = "satellite-ready"

[db]
port = 54322
major_version = 15

[api]
schemas = ["public"]

[functions.send_message_batch]
verify_jwt = true

[functions.pull_updates]
verify_jwt = true

[functions.send-test-notification]
verify_jwt = true
